### ISSUE TITLE
missing required property version

### ISSUE THREAD

**Issue by ferinoc** [springdoc/springdoc-openapi-maven-plugin#10]
Hi, 
I have following configuraiton:

`            <plugin>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-maven-plugin</artifactId>
                <version>1.0</version>
                <executions>
                    <execution>
                        <id>integration-test</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <apiDocsUrl>http://localhost:8080/v3/api-docs</apiDocsUrl>
                    <outputFileName>openapi.json</outputFileName>
                    <outputDir>${project.build.directory}</outputDir>
                </configuration>
            </plugin>
`
then following json is generated:
`
"openapi": "3.0.1",
  "info": {
    "title": "License plate 'reactive version' ",
    "description": ""
  },
.....
`

In intellij idea and also openapi-generator-maven-plugin, I'm getting error that required property version is missing.

I need to manually change it to:
 `
 "info": {
    "title": "License plate 'reactive version' ",
    "description": "",
    "version": "0.1"
  },
`
Do I miss something? 
Thank you.

**Comment by RandyHBH** [comment]
Could you post the logs?

**Comment by RandyHBH** [comment]
Also, @ferinoc could you check if in your pom.xml you have something like this 

```java
         <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <wait>1000</wait>
                    <maxAttempts>180</maxAttempts>
                    <jvmArguments>
                        -Dspring.application.admin.enabled=true
                    </jvmArguments>
                </configuration>
                <executions>
                    <execution>
                        <id>pre-integration-test</id>
                        <goals>
                            <goal>start</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>post-integration-test</id>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-maven-plugin</artifactId>
                <version>1.0</version>
                <executions>
                    <execution>
                        <id>integration-test</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by bnasslahsen** [comment]
@ferinoc, 

 This certainly comes from your version of OpenAPI Info section, which is not set in your code.
 If you are still having this issue, you can attach or add the link to the sample code to reproduce it and we will give you the guidance, how you can resolve it.
