### ISSUE TITLE
[Feature request] output in YAML/YML format, and preferably pretty printed (even for the current JSON one)

### ISSUE THREAD

**Issue by patpatpat123** [springdoc/springdoc-openapi-maven-plugin#12]
Hello,

First of all, a big thanks for this project.
This is a feature request, an idea to possibly make this project even more interesting, hope not to trouble.

Currently, this plugin is doing a great job in generating the JSON output.

First questions, can the output be pretty printed instead of the one liner?

Second question, would it be possible to add an option to have the output as (pretty printed) YAML/YML as well?

Thank you for your help.

**Comment by anthropaedic** [comment]
I can take a look

**Comment by vietcaominh** [comment]
I think it's good function too.

**Comment by anthropaedic** [comment]
Created pull request #15 for this issue.

**Comment by bnasslahsen** [comment]
@anthropaedic, 

 For pretty print, add the following property as argument: `-Dspringdoc.writer-with-default-pretty-printer=true`
 If you want the output in yaml format, just set the two following configuration propeties:
```xml
  <apiDocsUrl>http://localhost:8080/v3/api-docs.yaml</apiDocsUrl>
  <outputFileName>openapi.yaml</outputFileName>
```

 Here is a complete setting sample

```xml
<plugins>
	<plugin>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-maven-plugin</artifactId>
		<version>2.3.2.RELEASE</version>
		<executions>
			<execution>
				<id>pre-integration-test</id>
				<goals>
					<goal>start</goal>
				</goals>
			</execution>
			<execution>
				<id>post-integration-test</id>
				<goals>
					<goal>stop</goal>
				</goals>
			</execution>
		</executions>
	</plugin>
	<plugin>
		<groupId>org.springdoc</groupId>
		<artifactId>springdoc-openapi-maven-plugin</artifactId>
		<version>1.0</version>
		<executions>
			<execution>
				<id>integration-test</id>
				<goals>
					<goal>generate</goal>
				</goals>
			</execution>
		</executions>
		<configuration>
			<apiDocsUrl>http://localhost:8080/v3/api-docs.yaml
			</apiDocsUrl>
			<outputFileName>openapi.yaml</outputFileName>
		</configuration>
	</plugin>
</plugins>
```

**Comment by patpatpat123** [comment]
@bnasslahsen 
But it is achieving it in a rather unfriendly manner.
First of all, there are no clear indication of this magical -Dspringdoc.writer-with-default-pretty-printer=true
Second, it is rather magical to have those <apiDocsUrl>http://localhost:8080/v3/api-docs.yaml</apiDocsUrl>
  <outputFileName>openapi.yaml</outputFileName> to decide a yaml output.

Would it be possible to have a more objective judgement on your statement "the existing configuration allows to achieve the PR goal". While it is true manipulating rather not descriptive properties can have the same output, (well, I an also feed the json to a python converter that will pretty print and convert to yaml on a separate job, it "does the job").

Having more descriptive, self explanatory, proper configuration directly on the maven plugin block without hidden magical -Dparameter would be an improvement worth "not just closing".

Thank you
