### ISSUE TITLE
UI and generated json display ->  integer($int64) instead of long

### ISSUE THREAD

**Issue by patpatpat123** [springdoc/springdoc-openapi-maven-plugin#13]
Hello,

Just a small thing I wanted to report.
On a java primitive long, such as:

`   
 @Schema(description = "why integer($int64)?")
    private long someLongPrimitive;
`

The plugin is generating 

`
"someLongPrimitive": {
            "type": "integer",
            "description": "why integer($int64)?",
            "format": "int64"
          },
`

And the UI, following the json displays 

`
someLongPrimitive* | integer($int64)
`

Is it possible to call a primitive long, long?
Hope not to trouble.
Thank you

**Comment by bnasslahsen** [comment]
@patpatpat123, 

 You can have a look at the documentation of DataTypes:
 - https://swagger.io/docs/specification/data-models/data-types/#numbers
