### ISSUE TITLE
Yaml files are still published as json files

### ISSUE THREAD

**Issue by maddingo** [springdoc/springdoc-openapi-maven-plugin#23]
Even if I modify the apiDocsUrl to http://localhost:8080/v3/api-docs.yaml and the outputFileName to openapi.yaml. The artifact is still attached as a json file

**Comment by bnasslahsen** [comment]
@maddingo, 

 please see the answer here https://github.com/springdoc/springdoc-openapi-maven-plugin/issues/12
If you believe you are facing an issue, please make sure you provide a [Minimal, Reproducible Example - with HelloController ](https://stackoverflow.com/help/minimal-reproducible-example)that reproduces the problem

**Comment by maddingo** [comment]
@bnasslahsen I understand the settings. Please have a lookat the example in https://github.com/maddingo/minimal-spring-boot

The README.md explains what I mean.

**Comment by bnasslahsen** [comment]
Thank you for your contribution @maddingo. 
I have merged your PR and made some changes:
- It would simpler to keep the original file extension and leave it out of the box, without adding extra property

You can test with the latest `SNAPSHOT`, and if you find it OK for your case, we can release it very soon.

**Comment by maddingo** [comment]
Thanks @bnasslahsen, it works now as expected.I appreciate thatyou want to release a new version soon.

**Comment by bnasslahsen** [comment]
@maddingo, 

 Version 1.3 is now available on maven central.
