### ISSUE TITLE
Zombie process

### ISSUE THREAD

**Issue by Lopfest** [springdoc/springdoc-openapi-maven-plugin#27]
When executing the verify maven phase and generating the openapi.json file, maven finishes with success, however the java process associated with it running on port 9001 is not exited and you have to kill it every time you want to run verify phase again.

Dependencies used:
- springdoc-openapi-ui 1.5.9
- springdoc-openapi-maven-plugin 1.3

**Comment by Ligerd** [comment]
Maybe you found a solution because I have faced the same problem?

**Comment by lurkinme** [comment]
@Lopfest The plugin just saves the file during integration test phase. If you use the plugin along with openapi-diff-maven then change the phase of openapi-diff-maven from 'integration-test' to 'verify'. In my case zombie process appeared when the openapi-diff-maven was preventing the post-integration-test to run stop goal.

**Comment by bnasslahsen** [comment]
not reproducible.

**Comment by ricardojlrufino** [comment]
If i run: mvn integration-test
the process still running ... 

mvn -v
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /opt/apache-maven-3.8.5

java -version
openjdk version "1.8.0_342"

uname -a
Linux xx-note 5.4.0-107-generic #121~18.04.1-Ubuntu SMP Thu Mar 24 17:21:33 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bnasslahsen** [comment]
@ricardojlrufino see the documentation, as you are missing additional configuration:
- https://springdoc.org/v2/#maven-plugin

If you are still running the issue after updating your configuration, Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

**Comment by GrafTo1975** [comment]
Had the same problem when building locally in IntelliJ. Looks like the process doesn´t terminate if openapi.json is open in the editor. When closing the editor tab before building the process terminates correctly. Maybe it helps...

Regards
Tobias

**Comment by felixhix** [comment]
I have the same problem, but regardless of whether it is started via IntelliJ or via the external console (Bash). Each time a zombie process with port 9001 remains. `openapi.json`gets generated, tests completed. Sticked to the default values in the configuration.

Dependencies used:

```
OpenJDK 17
springdoc-openapi-starter-webmvc-api 2.5
springdoc-openapi-maven-plugin 1.4
```

Regards
Felix
