### ISSUE TITLE
Maven plugin does not offer equivalent of 'forkProperties'

### ISSUE THREAD

**Issue by planetf1** [springdoc/springdoc-openapi-maven-plugin#28]
I have a maven build where we would like to use springdoc to pull the generated api spec. Before moving to https we used the 'generate' target of the plugin which worked fine.

Since mandating https we need to be able to specify some additional jvm parameters (ie -Dserver.ssl.trust-store=....) but there is no option to do this (other than probably setting in maven's invocation)

The gradle plugin does offer a 'forkProperties' option which appears to do this. Is there a possibility to add this to the maven plugin?

**Comment by bnasslahsen** [comment]
@planetf1, 

There are no plans to add this properties for now.
Feel free to propose a PR, if you feel it useful for the community.
