### ISSUE TITLE
Provide configuration for prettyPrint output

### ISSUE THREAD

**Issue by d-baer** [springdoc/springdoc-openapi-maven-plugin#30]
Would be awesome if the plugin would offer a configuration for a pretty output (line breaks, indentation).

**Comment by bnasslahsen** [comment]
use property: `springdoc.writer-with-default-pretty-printer`

**Comment by d-baer** [comment]
Nice, for everyone having the same issue: [https://springdoc.org/#springdoc-openapi-core-properties](https://springdoc.org/#springdoc-openapi-core-properties)
