### ISSUE TITLE
Update to a supported version of Spring Boot

### ISSUE THREAD

**Issue by d-baer** [springdoc/springdoc-openapi-maven-plugin#31]
Spring Boot `2.0.9.RELEASE` is EOL since 2019-03-01 (see https://spring.io/projects/spring-boot#support). Update to a more recent version (`2.6.x`)

**Comment by bnasslahsen** [comment]
There is no issue with 2.6.x version!

**Comment by d-baer** [comment]
Sorry, maybe I was not clear enough. Talking about that: https://github.com/springdoc/springdoc-openapi-maven-plugin/blob/master/pom.xml#L54

**Comment by bnasslahsen** [comment]
feel free to propose a PR!
