### ISSUE TITLE
Add -Dspringdoc.writer-with-default-pretty-printer as maven plugin configuration parameter

### ISSUE THREAD

**Issue by ilyavy** [springdoc/springdoc-openapi-maven-plugin#39]
Use case:
We generate open-api documentation as part of the development process, and then commit the documentation to the repository. Developers use `mvn verify`, but sometimes they forget about this cumbersome system parameter, and commit one-line generated open-api document to git. It would be much more convenient and practical to have this parameter as maven plugin configuration parameter.

**Comment by bnasslahsen** [comment]
use `[springdoc properties](https://springdoc.org/#properties)` directly.
