### ISSUE TITLE
Springdoc-openapi-maven-plugin without springboot

### ISSUE THREAD

**Issue by milossamek** [springdoc/springdoc-openapi-maven-plugin#41]
hello,

is there any simple way how to integrate **springdoc-openapi-maven-plugin** for the `Spring WebMvc` framework.

Currently I see we need to run application in integration tests via `spring-boot-maven-plugin`, but I don't see any example to run it only with Spring WebMvc.

Do you have any guide for this?

Thanks for your help,
Milos

**Comment by bnasslahsen** [comment]
Nothing planned for that
