### ISSUE TITLE
Auto JSON format openapi.json

### ISSUE THREAD

**Issue by pavleprica** [springdoc/springdoc-openapi-maven-plugin#42]
Hey team,

While using this plugin, I thought it might be cool to have JSON auto-formatting. 

When generating the `openapi.json` file it creates a big one-liner. I know that people don't sit around and read the schema generated, but it comes in handy when you want to test quickly if your schema is generated the way you want it to be.

This might impact in a way that new dependencies are added to not write the whole formatted, what are your thoughts? :)

**Comment by capsuleman** [comment]
On my project, yaml documentation is generated, it is much more human-readable :-)

**Comment by pavleprica** [comment]
That's a fair point indeed. 😄
Though I guess it's also a matter of habit. 😄

**Comment by fabricio-entringer** [comment]
> On my project, yaml documentation is generated, it is much more human-readable :-)

Hello @capsuleman , how can you set it to generate yaml instead of json format? It didn't work for me!  Could you please give me a help with this case?

**Comment by apigitlabs** [comment]
@fabricio-entringer you can add <outputFileName>openapi.yaml</outputFileName> in <configuration> section to get .yaml instead of .json. However, the yaml is still a one-line file in my case

**Comment by bnasslahsen** [comment]
This feature is already in place #12
To format the json correctly use the `springdoc-openapi` property as argument of your maven goal: `-Dspringdoc.writer-with-default-pretty-printer=true`
