### ISSUE TITLE
Created Openapi.json file changes each time

### ISSUE THREAD

**Issue by saharazizighannad** [springdoc/springdoc-openapi-maven-plugin#47]
Every time I have a new controller or api and want to run the mvn to add it to `openapi.json` file, the new file has some changes in object orders. It makes it really difficult in terms of code review in pull request b/c basically lots of line is just been moved to a new place. Is there anyway to skip this ordering changes?

**Comment by bnasslahsen** [comment]
@saharazizighannad, 

Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi-maven-plugin/blob/65c09dd192165bd933a65e75f032cb3b1a0a5982/CONTRIBUTING.adoc).

Make sure you provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem
