### ISSUE TITLE
Runtime or buildtime?

### ISSUE THREAD

**Issue by Luthien-in-edhil** [springdoc/springdoc-openapi-maven-plugin#51]
While upgrading from the old Swagger Springfox library to Springdoc, I was reading [this Baeldung article](https://www.baeldung.com/spring-rest-openapi-documentation) which mentioned this springdoc-openapi Maven Plugin.

The [readme.md](https://github.com/springdoc/springdoc-openapi-maven-plugin/blob/master/README.md) here on Github starts with:

> The aim of springdoc-openapi-maven-plugin is to generate json and yaml OpenAPI description **during runtime**

though, as I understand it, this plugin is actually providing the documentation at _build time_ instead, as is implicit in the Baeldung article, and clarified by [this SO answer](https://stackoverflow.com/questions/59616165/what-is-the-function-of-springdoc-openapi-maven-plugin-configuration-apidocsurl) by [diegomtassis](https://stackoverflow.com/users/2260761/diegomtassis):

> By using springdoc-openapi-ui you generate the documentation (html, json & yaml) at runtime, when your app is deployed.
**In some scenarios you may want to have the documentation at build time, and that's what the springdoc-openapi-maven-plugin is for.** In order for it to work you need as well to have your application started using spring-boot during the integration phase, as [explained in the documentation](https://github.com/springdoc/springdoc-openapi-maven-plugin).

It might prevent some confusion if the readme was clear about that :)

**Comment by bnasslahsen** [comment]
@Luthien-in-edhil,

Thank you for your feedback. 
We will leave the documentation as it is right now.
