### ISSUE TITLE
Plugin do not generate java.util.Date correctly

### ISSUE THREAD

**Issue by fsahler** [springdoc/springdoc-openapi-maven-plugin#52]
Hi,
here is a sample-code:

_@ApiModelProperty(notes = "Datum an dem das Onboarding zuletzt inaktiv geschaltet wurde")
@JsonProperty("deactivated_date")
@Size (max=32)
private Date deactivatedDate;_

The generator turns this code into  

_deactivated_date:
  type: string
  format: date-time_

and not into

_deactivated_date:
  type: string
  format: date-time
  maxLength: 32_

Is there any way to fix this problem?

**Comment by bnasslahsen** [comment]
No to conform to contributions to this repository. 
You should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi-maven-plugin/blob/65c09dd192165bd933a65e75f032cb3b1a0a5982/CONTRIBUTING.adoc).
