### ISSUE TITLE
Plugin does not generate responses correctly

### ISSUE THREAD

**Issue by fsahler** [springdoc/springdoc-openapi-maven-plugin#53]
Hi,
Here is a sample code:

_@ApiResponse(responseCode = "400", description = RC_400,       
>content = @Content(mediaType = MediaType.APPLICATION_JSON_VALUE,
>>schema = @Schema (type = "string", maxLength = 200, minLength = 10, pattern = "[a-zA-Z]",
 >>>implementation = Error.class))),_

from this the generator generates:

_"400":
> description: Bad Request
 >content:
  >>application/json:
  >>>schema:
  >>>>type: string_

But he would have to generate that instead:

_"400":
>description: Bad Request
>content:
>> application/json:
 >>>schema:
>>>>maxLength: 200
>>>>minLength: 10
>>>>pattern: "[a-zA-Z]"
>>>>type: string_

Is there any way to fix this problem?

**Comment by bnasslahsen** [comment]
No to conform to contributions to this repository. 
You should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi-maven-plugin/blob/65c09dd192165bd933a65e75f032cb3b1a0a5982/CONTRIBUTING.adoc).
