### ISSUE TITLE
Plugin does not generate list of objects correctly

### ISSUE THREAD

**Issue by fsahler** [springdoc/springdoc-openapi-maven-plugin#54]
Hi,
here is a sample-code:

_@ApiModelProperty(notes = "Liste der ProduktgruppenIds")
@JsonProperty("produktgruppenids")
@Size (min=1, max=80)
private List< @Min(1) @Max(100) Long> produktgruppenIds = new ArrayList<>();_

The result of the generator is:

_produktgruppenids:
>maxItems: 80
>minItems: 1
>type: array
>items:
>>type: integer
>>format: int64_

But the result should look like this:

_produktgruppenids:
>maxItems: 80
>minItems: 1
>type: array
>items:
>>maximum: 100
>>minimum: 1
>>type: integer
>>format: int64_

Gibt es eine Möglichkeit, dieses Problem zu beheben?

**Comment by bnasslahsen** [comment]
No to conform to contributions to this repository. 
You should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi-maven-plugin/blob/65c09dd192165bd933a65e75f032cb3b1a0a5982/CONTRIBUTING.adoc).
