### ISSUE TITLE
Are there locations configuration?

### ISSUE THREAD

**Issue by jsh1986** [springdoc/springdoc-openapi-maven-plugin#57]
I am looking for `locations` configuration.

when I use 'swagger-maven-plugin', I can use 'locations' configuration
https://github.com/kongchen/swagger-maven-plugin#configuration-for-apisource
![image](https://user-images.githubusercontent.com/710143/210743603-472b55fd-398a-4e34-8e77-028f86bac30a.png)

I am looking for similar configuration in 'springdoc-openapi-maven-plugin'. but, I cannot find.

**Comment by bnasslahsen** [comment]
You can use the springdoc-openapi properties:

https://springdoc.org/#springdoc-openapi-core-properties such as `springdoc.packages-to-scan`




<br class="Apple-interchange-newline">
